from pp.agents.herbivore import Herbivore, herbivores_den
from pp.agents.plant import Plant
from pp.agents.predator import Predator, predators_den


def mock_input():
    return [
        herbivores_den,
        herbivores_den,
        herbivores_den,
        herbivores_den,
        herbivores_den,
        herbivores_den,
        predators_den,
        predators_den,
        predators_den,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Herbivore,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Plant,
        Predator,
        Predator,
        Predator,
        Predator,
        Predator
    ]